"""
Smart Water Purification & Quality Monitoring System — Prototype App
Run with: streamlit run app.py

Requires artifacts/model.pkl, artifacts/metrics.json, artifacts/feature_importance.json,
artifacts/imputer_values.json, artifacts/model_comparison.json
(generated by running train_model.py first).
"""

import json
import pickle
import time
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

ARTIFACT_DIR = Path("artifacts")

st.set_page_config(
    page_title="Smart Water Purification & Quality Monitoring",
    page_icon="💧",
    layout="wide",
)

# ---------- Load artifacts ----------
@st.cache_resource
def load_artifacts():
    with open(ARTIFACT_DIR / "model.pkl", "rb") as f:
        bundle = pickle.load(f)
    with open(ARTIFACT_DIR / "metrics.json") as f:
        metrics = json.load(f)
    with open(ARTIFACT_DIR / "feature_importance.json") as f:
        importance = json.load(f)
    with open(ARTIFACT_DIR / "imputer_values.json") as f:
        medians = json.load(f)
    comparison_path = ARTIFACT_DIR / "model_comparison.json"
    comparison = json.load(open(comparison_path)) if comparison_path.exists() else None
    return bundle, metrics, importance, medians, comparison


try:
    bundle, metrics, importance, medians, comparison = load_artifacts()
    model = bundle["model"]
    model_name = bundle["model_name"]
    FEATURES = bundle["features"]
except FileNotFoundError:
    st.error(
        "Model artifacts not found. Run `python train_model.py` first to train "
        "the model and generate the `artifacts/` folder."
    )
    st.stop()

# ---------- Load heavy-metal model artifacts (optional Tab 4) ----------
@st.cache_resource
def load_hm_artifacts():
    with open(ARTIFACT_DIR / "model_heavy_metals.pkl", "rb") as f:
        bundle_hm = pickle.load(f)
    with open(ARTIFACT_DIR / "metrics_heavy_metals.json") as f:
        metrics_hm = json.load(f)
    with open(ARTIFACT_DIR / "feature_importance_heavy_metals.json") as f:
        importance_hm = json.load(f)
    return bundle_hm, metrics_hm, importance_hm


HAS_HM_MODEL = (ARTIFACT_DIR / "model_heavy_metals.pkl").exists()
if HAS_HM_MODEL:
    bundle_hm, metrics_hm, importance_hm = load_hm_artifacts()
    model_hm = bundle_hm["model"]
    model_hm_name = bundle_hm["model_name"]
    FEATURES_HM = bundle_hm["features"]

# Heavy metal / contaminant slider ranges — based on training data distribution
HM_RANGES = {
    "aluminium": (0.0, 5.0, 0.1), "ammonia": (0.0, 30.0, 5.0), "arsenic": (0.0, 1.0, 0.02),
    "barium": (0.0, 5.0, 1.0), "cadmium": (0.0, 0.05, 0.002), "chloramine": (0.0, 10.0, 3.0),
    "chromium": (0.0, 1.0, 0.1), "copper": (0.0, 2.0, 0.2), "flouride": (0.0, 2.0, 0.5),
    "bacteria": (0.0, 1.0, 0.1), "viruses": (0.0, 1.0, 0.1), "lead": (0.0, 0.2, 0.02),
    "nitrates": (0.0, 20.0, 5.0), "nitrites": (0.0, 3.0, 0.5), "mercury": (0.0, 0.01, 0.001),
    "perchlorate": (0.0, 90.0, 15.0), "radium": (0.0, 8.0, 2.0), "selenium": (0.0, 0.1, 0.02),
    "silver": (0.0, 0.5, 0.05), "uranium": (0.0, 0.1, 0.02),
}
HM_SAFE_LIMITS = {  # rough WHO/EPA style reference limits, for the "why unsafe" explanation
    "arsenic": 0.01, "lead": 0.01, "mercury": 0.006, "uranium": 0.03, "cadmium": 0.003,
    "chromium": 0.05, "nitrates": 10.0, "bacteria": 0.0, "viruses": 0.0,
}

# Reasonable slider ranges based on the training data distribution
FEATURE_RANGES = {
    "ph": (0.0, 14.0, 7.0),
    "Hardness": (0.0, 350.0, 200.0),
    "Solids": (0.0, 55000.0, 20000.0),
    "Chloramines": (0.0, 14.0, 7.0),
    "Sulfate": (0.0, 500.0, 330.0),
    "Conductivity": (100.0, 800.0, 420.0),
    "Organic_carbon": (0.0, 30.0, 14.0),
    "Trihalomethanes": (0.0, 130.0, 66.0),
    "Turbidity": (0.0, 7.0, 4.0),
}

FEATURE_UNITS = {
    "ph": "",
    "Hardness": "mg/L",
    "Solids": "ppm",
    "Chloramines": "ppm",
    "Sulfate": "mg/L",
    "Conductivity": "μS/cm",
    "Organic_carbon": "ppm",
    "Trihalomethanes": "μg/L",
    "Turbidity": "NTU",
}


def predict(values: dict):
    row = pd.DataFrame([[values[f] for f in FEATURES]], columns=FEATURES)
    pred = model.predict(row)[0]
    proba = model.predict_proba(row)[0][1]  # probability of "Safe" (class 1)
    return pred, proba


# ---------- Session state for alert log + live stream ----------
if "alert_log" not in st.session_state:
    st.session_state.alert_log = []
if "stream_data" not in st.session_state:
    st.session_state.stream_data = []
if "streaming" not in st.session_state:
    st.session_state.streaming = False

st.title("💧 Smart Water Purification & Quality Monitoring System")
st.caption(
    "Software prototype simulating the ML decision-making layer that would run "
    "on the ESP32 edge device in the full deployed system."
)

tab_labels = ["🔴 Live Simulation", "📊 Model Insights", "🚨 Alert System"]
if HAS_HM_MODEL:
    tab_labels.append("⛏️ Heavy Metal / Mining Check")
    tab1, tab2, tab3, tab4 = st.tabs(tab_labels)
else:
    tab1, tab2, tab3 = st.tabs(tab_labels)

# ================= TAB 1: LIVE SIMULATION =================
with tab1:
    st.subheader("Simulate a Real-Time IoT Sensor Reading")
    st.write(
        "Adjust the sliders to mimic output-sensor readings after the purification "
        "stages, then check the safety prediction."
    )

    col1, col2 = st.columns([1, 1])
    values = {}

    with col1:
        for f in FEATURES[:5]:
            lo, hi, default = FEATURE_RANGES[f]
            unit = FEATURE_UNITS[f]
            label = f"{f} ({unit})" if unit else f
            values[f] = st.slider(label, lo, hi, default, key=f"slider_{f}")

    with col2:
        for f in FEATURES[5:]:
            lo, hi, default = FEATURE_RANGES[f]
            unit = FEATURE_UNITS[f]
            label = f"{f} ({unit})" if unit else f
            values[f] = st.slider(label, lo, hi, default, key=f"slider_{f}")

    st.divider()

    pred, proba = predict(values)

    result_col, gauge_col = st.columns([1, 1])
    with result_col:
        if pred == 1:
            st.success("### ✅ SAFE — Water released to outlet tap")
            st.metric("Model confidence (Safe)", f"{proba*100:.1f}%")
        else:
            st.error("### ⛔ UNSAFE — Water release BLOCKED")
            st.metric("Model confidence (Unsafe)", f"{(1-proba)*100:.1f}%")
            # log this event for the Alert tab
            st.session_state.alert_log.append(
                {
                    "time": pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S"),
                    "confidence": round((1 - proba) * 100, 1),
                    "readings": values.copy(),
                }
            )

    with gauge_col:
        fig = go.Figure(
            go.Indicator(
                mode="gauge+number",
                value=proba * 100,
                title={"text": "Safety Score (%)"},
                gauge={
                    "axis": {"range": [0, 100]},
                    "bar": {"color": "darkblue"},
                    "steps": [
                        {"range": [0, 50], "color": "#ffcccc"},
                        {"range": [50, 100], "color": "#ccffcc"},
                    ],
                    "threshold": {
                        "line": {"color": "black", "width": 3},
                        "value": 50,
                    },
                },
            )
        )
        fig.update_layout(height=280, margin=dict(l=20, r=20, t=40, b=20))
        st.plotly_chart(fig, use_container_width=True)

    st.divider()

    # ----- Bonus: simulate sensor stream -----
    st.subheader("📡 Simulate Sensor Stream")
    st.write(
        "Auto-generates readings every couple seconds like a live IoT feed, "
        "with random noise around the current slider values."
    )

    stream_cols = st.columns([1, 1, 3])
    with stream_cols[0]:
        start = st.button("▶ Start stream", use_container_width=True)
    with stream_cols[1]:
        stop = st.button("⏹ Stop stream", use_container_width=True)
    with stream_cols[2]:
        n_points = st.slider("Points to generate", 5, 50, 15)

    if start:
        st.session_state.streaming = True
    if stop:
        st.session_state.streaming = False

    chart_placeholder = st.empty()
    status_placeholder = st.empty()

    if st.session_state.streaming:
        readings = []
        for i in range(n_points):
            if not st.session_state.streaming:
                break
            noisy = {
                f: max(FEATURE_RANGES[f][0], min(FEATURE_RANGES[f][1],
                       values[f] + np.random.normal(0, (FEATURE_RANGES[f][1] - FEATURE_RANGES[f][0]) * 0.03)))
                for f in FEATURES
            }
            p, pr = predict(noisy)
            readings.append(
                {"t": i, "safety_score": pr * 100, "status": "Safe" if p == 1 else "Unsafe"}
            )
            df_stream = pd.DataFrame(readings)
            fig2 = px.line(
                df_stream, x="t", y="safety_score", markers=True,
                title="Live Safety Score Feed", range_y=[0, 100],
            )
            fig2.add_hline(y=50, line_dash="dash", line_color="red")
            chart_placeholder.plotly_chart(fig2, use_container_width=True, key=f"stream_{i}")
            status_placeholder.write(
                f"Latest reading: **{readings[-1]['status']}** "
                f"(safety score {readings[-1]['safety_score']:.1f}%)"
            )
            time.sleep(1.5)
        st.session_state.streaming = False

# ================= TAB 2: MODEL INSIGHTS =================
with tab2:
    st.subheader(f"Model Performance — {model_name}")

    m1, m2, m3, m4, m5 = st.columns(5)
    m1.metric("Accuracy", f"{metrics['accuracy']*100:.1f}%")
    m2.metric("Precision", f"{metrics['precision']*100:.1f}%")
    m3.metric("Recall", f"{metrics['recall']*100:.1f}%")
    m4.metric("F1 Score", f"{metrics['f1']*100:.1f}%")
    m5.metric("ROC-AUC", f"{metrics['roc_auc']*100:.1f}%")

    col1, col2 = st.columns(2)

    with col1:
        st.write("**Confusion Matrix**")
        cm = np.array(metrics["confusion_matrix"])
        fig_cm = px.imshow(
            cm,
            text_auto=True,
            labels=dict(x="Predicted", y="Actual", color="Count"),
            x=["Unsafe (0)", "Safe (1)"],
            y=["Unsafe (0)", "Safe (1)"],
            color_continuous_scale="Blues",
        )
        fig_cm.update_layout(height=400)
        st.plotly_chart(fig_cm, use_container_width=True)

    with col2:
        st.write("**Feature Importance**")
        imp_df = pd.DataFrame(
            {"feature": list(importance.keys()), "importance": list(importance.values())}
        ).sort_values("importance", ascending=True)
        fig_imp = px.bar(imp_df, x="importance", y="feature", orientation="h")
        fig_imp.update_layout(height=400)
        st.plotly_chart(fig_imp, use_container_width=True)

    if comparison:
        st.write("**Model Comparison**")
        rows = []
        for name, vals in comparison.items():
            if name == "best_model":
                continue
            rows.append({"model": name, **{k: v for k, v in vals.items() if k != "confusion_matrix"}})
        st.dataframe(pd.DataFrame(rows), use_container_width=True, hide_index=True)

    with st.expander("ℹ️ How to read these metrics"):
        st.write(
            "- **Precision**: of the times we predicted Safe, how often it really was.\n"
            "- **Recall**: of all truly Safe samples, how many we correctly caught.\n"
            "- **Confusion matrix**: bottom-right = correctly predicted Safe; "
            "top-left = correctly predicted Unsafe; off-diagonal = errors.\n"
            "- For a drinking-water system, missing an Unsafe sample (false negative, "
            "top-right → not shown here since axes are flipped, check row 'Unsafe' vs "
            "predicted 'Safe') is the costliest error type."
        )

# ================= TAB 3: ALERT SYSTEM =================
with tab3:
    st.subheader("3-Tier Alert System")
    st.write(
        "When the model classifies a reading as **Unsafe**, the release valve stays "
        "closed and alerts fire across three tiers: on-site display, caretaker SMS, "
        "and the government trend dashboard."
    )

    if not st.session_state.alert_log:
        st.info(
            "No alerts yet. Go to **Live Simulation**, set slider values that produce "
            "an Unsafe reading, and it will appear here."
        )
    else:
        latest = st.session_state.alert_log[-1]

        st.error(
            f"### 🚨 UNSAFE WATER DETECTED — {latest['time']}\n"
            f"Model confidence: **{latest['confidence']}% Unsafe**"
        )

        c1, c2, c3 = st.columns(3)
        with c1:
            st.markdown("#### 🔴 On-site Display")
            st.warning("LED status: **RED**\nOutlet valve: **CLOSED**")
        with c2:
            st.markdown("#### 📱 Caretaker SMS")
            st.success(
                f"✅ Simulated SMS sent to ASHA worker:\n\n"
                f"\"Water quality ALERT at Unit #JH-04. "
                f"Reading unsafe as of {latest['time']}. "
                f"Please inspect filters.\""
            )
        with c3:
            st.markdown("#### 🏛️ Government Dashboard")
            st.info("Event logged to aggregated trend dashboard for Health Dept review.")

        st.divider()
        st.write("**Alert History**")
        hist_df = pd.DataFrame(
            [{"Time": a["time"], "Unsafe Confidence (%)": a["confidence"]} for a in st.session_state.alert_log]
        )
        st.dataframe(hist_df, use_container_width=True, hide_index=True)

        if st.button("Clear alert history"):
            st.session_state.alert_log = []
            st.rerun()

# ================= TAB 4: HEAVY METAL / MINING CHECK =================
if HAS_HM_MODEL:
    with tab4:
        st.subheader("⛏️ Heavy Metal & Mining-Contamination Check")
        st.write(
            f"Specialized model ({model_hm_name}) trained on heavy-metal and "
            "chemical/biological contaminant concentrations — targets acid mine "
            "drainage and mining-runoff-specific contamination (arsenic, lead, "
            "mercury, uranium, etc.) that the general potability model doesn't cover."
        )

        hm_col1, hm_col2, hm_col3, hm_col4 = st.columns(4)
        hm_values = {}
        cols_cycle = [hm_col1, hm_col2, hm_col3, hm_col4]
        for i, f in enumerate(FEATURES_HM):
            lo, hi, default = HM_RANGES.get(f, (0.0, 10.0, 1.0))
            with cols_cycle[i % 4]:
                step = round((hi - lo) / 100, 5) if hi > lo else 0.01
                hm_values[f] = st.number_input(
                    f, min_value=lo, max_value=hi, value=default, step=step,
                    key=f"hm_{f}", format="%.4f",
                )

        st.divider()

        hm_row = pd.DataFrame([[hm_values[f] for f in FEATURES_HM]], columns=FEATURES_HM)
        hm_pred = model_hm.predict(hm_row)[0]
        hm_proba = model_hm.predict_proba(hm_row)[0][1]

        res_col, gauge_col = st.columns([1, 1])
        with res_col:
            if hm_pred == 1:
                st.success("### ✅ SAFE — No significant heavy-metal / mining contamination detected")
                st.metric("Model confidence (Safe)", f"{hm_proba*100:.1f}%")
            else:
                st.error("### ⛔ UNSAFE — Heavy-metal / mining contamination detected")
                st.metric("Model confidence (Unsafe)", f"{(1-hm_proba)*100:.1f}%")

                # Flag which specific contaminants exceed reference safe limits
                exceeded = [
                    f for f, limit in HM_SAFE_LIMITS.items()
                    if f in hm_values and hm_values[f] > limit
                ]
                if exceeded:
                    st.warning(
                        "Contaminants above reference safe limits: **"
                        + ", ".join(exceeded) + "**"
                    )
                st.session_state.alert_log.append(
                    {
                        "time": pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S"),
                        "confidence": round((1 - hm_proba) * 100, 1),
                        "readings": {**hm_values, "type": "heavy_metal"},
                    }
                )

        with gauge_col:
            fig_hm = go.Figure(
                go.Indicator(
                    mode="gauge+number",
                    value=hm_proba * 100,
                    title={"text": "Safety Score (%)"},
                    gauge={
                        "axis": {"range": [0, 100]},
                        "bar": {"color": "darkred"},
                        "steps": [
                            {"range": [0, 50], "color": "#ffcccc"},
                            {"range": [50, 100], "color": "#ccffcc"},
                        ],
                        "threshold": {"line": {"color": "black", "width": 3}, "value": 50},
                    },
                )
            )
            fig_hm.update_layout(height=280, margin=dict(l=20, r=20, t=40, b=20))
            st.plotly_chart(fig_hm, use_container_width=True)

        st.divider()
        st.subheader("Model Performance")
        h1, h2, h3, h4, h5 = st.columns(5)
        h1.metric("Accuracy", f"{metrics_hm['accuracy']*100:.1f}%")
        h2.metric("Precision", f"{metrics_hm['precision']*100:.1f}%")
        h3.metric("Recall", f"{metrics_hm['recall']*100:.1f}%")
        h4.metric("F1 Score", f"{metrics_hm['f1']*100:.1f}%")
        h5.metric("ROC-AUC", f"{metrics_hm['roc_auc']*100:.1f}%")

        imp_hm_df = pd.DataFrame(
            {"contaminant": list(importance_hm.keys())[:10],
             "importance": list(importance_hm.values())[:10]}
        ).sort_values("importance", ascending=True)
        fig_imp_hm = px.bar(
            imp_hm_df, x="importance", y="contaminant", orientation="h",
            title="Top 10 Most Important Contaminants",
        )
        st.plotly_chart(fig_imp_hm, use_container_width=True)
